/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketQueueRouteImport } from './routes/ticket-queue'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveChatsRouteImport } from './routes/live-chats'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TicketQueueAgentIdRouteImport } from './routes/ticket-queue_.$agentId'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminRecordsRouteImport } from './routes/admin/records'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminChatsRouteImport } from './routes/admin/chats'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAiAssistantRouteImport } from './routes/admin/ai-assistant'
import { Route as AdminAgentsRouteImport } from './routes/admin/agents'
import { Route as AdminTicketsTicketIdRouteImport } from './routes/admin/tickets.$ticketId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers.$customerId'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin/agents.$agentId'

const TicketQueueRoute = TicketQueueRouteImport.update({
  id: '/ticket-queue',
  path: '/ticket-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveChatsRoute = LiveChatsRouteImport.update({
  id: '/live-chats',
  path: '/live-chats',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TicketQueueAgentIdRoute = TicketQueueAgentIdRouteImport.update({
  id: '/ticket-queue_/$agentId',
  path: '/ticket-queue/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAssistantRoute = AdminAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsTicketIdRoute = AdminTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminTicketsRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AdminAgentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/live-chats': typeof LiveChatsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/ticket-queue': typeof TicketQueueRoute
  '/admin/agents': typeof AdminAgentsRouteWithChildren
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/ticket-queue/$agentId': typeof TicketQueueAgentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/live-chats': typeof LiveChatsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/ticket-queue': typeof TicketQueueRoute
  '/admin/agents': typeof AdminAgentsRouteWithChildren
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/ticket-queue/$agentId': typeof TicketQueueAgentIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/help': typeof HelpRoute
  '/live-chats': typeof LiveChatsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/ticket-queue': typeof TicketQueueRoute
  '/admin/agents': typeof AdminAgentsRouteWithChildren
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/ticket-queue_/$agentId': typeof TicketQueueAgentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/help'
    | '/live-chats'
    | '/login'
    | '/notifications'
    | '/performance'
    | '/settings'
    | '/signup'
    | '/ticket-queue'
    | '/admin/agents'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/records'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tickets'
    | '/ticket-queue/$agentId'
    | '/admin/'
    | '/admin/agents/$agentId'
    | '/admin/customers/$customerId'
    | '/admin/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/live-chats'
    | '/login'
    | '/notifications'
    | '/performance'
    | '/settings'
    | '/signup'
    | '/ticket-queue'
    | '/admin/agents'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/records'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tickets'
    | '/ticket-queue/$agentId'
    | '/admin'
    | '/admin/agents/$agentId'
    | '/admin/customers/$customerId'
    | '/admin/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/help'
    | '/live-chats'
    | '/login'
    | '/notifications'
    | '/performance'
    | '/settings'
    | '/signup'
    | '/ticket-queue'
    | '/admin/agents'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/records'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/tickets'
    | '/ticket-queue_/$agentId'
    | '/admin/'
    | '/admin/agents/$agentId'
    | '/admin/customers/$customerId'
    | '/admin/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  HelpRoute: typeof HelpRoute
  LiveChatsRoute: typeof LiveChatsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PerformanceRoute: typeof PerformanceRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TicketQueueRoute: typeof TicketQueueRoute
  TicketQueueAgentIdRoute: typeof TicketQueueAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket-queue': {
      id: '/ticket-queue'
      path: '/ticket-queue'
      fullPath: '/ticket-queue'
      preLoaderRoute: typeof TicketQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-chats': {
      id: '/live-chats'
      path: '/live-chats'
      fullPath: '/live-chats'
      preLoaderRoute: typeof LiveChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ticket-queue_/$agentId': {
      id: '/ticket-queue_/$agentId'
      path: '/ticket-queue/$agentId'
      fullPath: '/ticket-queue/$agentId'
      preLoaderRoute: typeof TicketQueueAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-assistant': {
      id: '/admin/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/admin/ai-assistant'
      preLoaderRoute: typeof AdminAiAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/$ticketId': {
      id: '/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AdminTicketsTicketIdRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof AdminAgentsRoute
    }
  }
}

interface AdminAgentsRouteChildren {
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
}

const AdminAgentsRouteChildren: AdminAgentsRouteChildren = {
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
}

const AdminAgentsRouteWithChildren = AdminAgentsRoute._addFileChildren(
  AdminAgentsRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminTicketsRouteChildren {
  AdminTicketsTicketIdRoute: typeof AdminTicketsTicketIdRoute
}

const AdminTicketsRouteChildren: AdminTicketsRouteChildren = {
  AdminTicketsTicketIdRoute: AdminTicketsTicketIdRoute,
}

const AdminTicketsRouteWithChildren = AdminTicketsRoute._addFileChildren(
  AdminTicketsRouteChildren,
)

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRouteWithChildren
  AdminAiAssistantRoute: typeof AdminAiAssistantRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTicketsRoute: typeof AdminTicketsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRouteWithChildren,
  AdminAiAssistantRoute: AdminAiAssistantRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTicketsRoute: AdminTicketsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  HelpRoute: HelpRoute,
  LiveChatsRoute: LiveChatsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PerformanceRoute: PerformanceRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TicketQueueRoute: TicketQueueRoute,
  TicketQueueAgentIdRoute: TicketQueueAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
